//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello_Travellers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class React
    {
        public Nullable<int> ReactStatus { get; set; }
        public int PostID { get; set; }
        public string Username { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
