//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello_Travellers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public string Context { get; set; }
        public string ContextID { get; set; }
        public string Reason { get; set; }
        public string ReporterUsername { get; set; }
        public string Status { get; set; }
        public virtual User User { get; set; }
    }
}
